---
name: actions - jq

description: 'actions - Run jq'

runs:
    using: composite
    steps:
        - name: run jq
          run: |
            echo "jq version: $(jq --version)"
            echo "jq output: $(jq -n '{foo: "bar"}')"
          shell: bash
