---
name: workflow - jq

on:
  push:
    branches:
      - main

jobs:
  test-workflow-run-jq:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: workflow >> Run jq
        run: |
          echo "jq version: $(jq --version)"
          echo "jq output: $(jq -n '{foo: "bar"}')"

      - uses: './.github/actions/jq'
        name: action >> Run jq
