---
name: workflow - jq

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - name: Run jq
          run: |
            echo "jq version: $(jq --version)"
            echo "jq output: $(jq -n '{foo: "bar"}')"
